// Types
export type {
  ApiCalendarEventResponse,
  ApiCalendarResponse,
  ApiCalendarsResponse,
  ApiCalendarEventsResponse,
  Calendar,
  CalendarCreateBody,
  CalendarEvent,
  CalendarEventCreateBody,
  CalendarEventQueryArgs,
  CalendarEventUpdateBody,
  CalendarEventsResponse,
  CalendarType,
  CalendarUpdateBody,
  CalendarsResponse,
  EventAttendee,
  EventRecurrence,
  EventReminder,
  AttendanceStatus,
  AttendanceBody,
  ExternalCalendarCreateBody,
  ExternalCalendarUpdateBody,
  CalendarSyncStatus,
  CalendarSyncResult,
} from './calendars-types'

export { DEFAULT_CALENDAR_COLOR } from './calendars-types'

// API & Hooks from RTK Query
export {
  useCreateCalendarMutation,
  useCreateCalendarEventMutation,
  useDeleteCalendarMutation,
  useDeleteCalendarEventMutation,
  useGetCalendarByIdQuery,
  useGetCalendarEventByIdQuery,
  useGetCalendarsQuery,
  useGetEventsInTimeRangeQuery,
  useSearchEventsQuery,
  useUpdateCalendarMutation,
  useUpdateCalendarEventMutation,
  usePostEventAttendanceMutation,
  useCreateExternalCalendarMutation,
  useDeleteExternalCalendarMutation,
  useGetExternalCalendarsQuery,
  useGetExternalCalendarQuery,
  useGetSyncStatusQuery,
  useTriggerSyncMutation,
  useUpdateExternalCalendarMutation,
} from './store/calendars-api'
