import { transformJson } from '../utils'

describe('transformJson', () => {
  it('should transform nested JSON with string properties', () => {
    const input = {
      Account_Security: {
        title: {
          string: 'Account Security',
        },
        totp: {
          title: {
            string: 'Two-Factor Authentication',
          },
          description: {
            string:
              'Two-factor authentication adds an extra layer of security to your account. Once enabled, you will be required to enter a unique code generated by an authenticator app on your phone each time you log in.',
          },
          verification_code: {
            title: {
              string: 'Verification Code',
            },
            description: {
              string:
                'Enter the verification code generated by your authenticator app.',
            },
          },
          save: {
            string: 'Save',
          },
        },
      },
    }

    const expectedOutput = {
      Account_Security: {
        title: 'Account Security',
        totp: {
          title: 'Two-Factor Authentication',
          description:
            'Two-factor authentication adds an extra layer of security to your account. Once enabled, you will be required to enter a unique code generated by an authenticator app on your phone each time you log in.',
          verification_code: {
            title: 'Verification Code',
            description:
              'Enter the verification code generated by your authenticator app.',
          },
          save: 'Save',
        },
      },
    }

    expect(transformJson(input)).toEqual(expectedOutput)
  })

  it('should handle empty JSON', () => {
    const input = {}
    const expectedOutput = {}
    expect(transformJson(input)).toEqual(expectedOutput)
  })

  it('should handle JSON without string properties', () => {
    const input = {
      key1: 'value1',
      key2: {
        key3: 'value3',
      },
    }
    const expectedOutput = {
      key1: 'value1',
      key2: {
        key3: 'value3',
      },
    }
    expect(transformJson(input)).toEqual(expectedOutput)
  })

  it('should handle JSON with mixed properties', () => {
    const input = {
      key1: 'value1',
      key2: {
        string: 'value2',
      },
      key3: {
        key4: {
          string: 'value4',
        },
        key5: 'value5',
      },
    }
    const expectedOutput = {
      key1: 'value1',
      key2: 'value2',
      key3: {
        key4: 'value4',
        key5: 'value5',
      },
    }
    expect(transformJson(input)).toEqual(expectedOutput)
  })

  it('should handle JSON with arrays', () => {
    const input = {
      key1: 'value1',
      key2: [
        {
          string: 'value2',
        },
        {
          key3: 'value3',
        },
      ],
    }
    const expectedOutput = {
      key1: 'value1',
      key2: [
        {
          string: 'value2',
        },
        {
          key3: 'value3',
        },
      ],
    }
    expect(transformJson(input)).toEqual(expectedOutput)
  })
})
