FROM node:22-slim

ARG USERNAME=vscode
ARG WORKSPACE=/SOGo
ARG USER_ID=1000
ARG GROUP_ID=1000

RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo \
    git \
    curl \
    bash \
    openssh-client \
    procps \
    ncurses-bin \
    && rm -rf /var/lib/apt/lists/*

RUN usermod -l ${USERNAME} -u ${USER_ID} node \
    && groupmod -n ${USERNAME} -g ${GROUP_ID} node \
    && usermod -d /home/${USERNAME} -m ${USERNAME} \
    && echo "${USERNAME} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME}

RUN npm install -g npm-check-updates

RUN curl -fsSL https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash

RUN mkdir -p ${WORKSPACE} ${WORKSPACE}/.next && chown -R ${USERNAME}:${USERNAME} ${WORKSPACE}

COPY --chown=${USERNAME}:${USERNAME} .devcontainer/container-entrypoint.sh /container-entrypoint
RUN chmod +x /container-entrypoint
COPY --chown=${USERNAME}:${USERNAME} .devcontainer/files/bashrc /home/${USERNAME}/.bashrc

ENV PATH="/home/vscode/.local/bin:$PATH"

WORKDIR ${WORKSPACE}

USER ${USERNAME}