import { VCard } from '@/features/address_books/address-books-types'
import { NextResponse } from 'next/server'

const data: VCard[] = [
  {
    id: '1',
    version: '4.0',
    firstName: 'John',
    lastName: 'Doe',
    middleName: 'A.',
    prefix: 'Mr.',
    suffix: 'Jr.',
    nickname: 'Johnny',
    title: 'Software Engineer',
    organization: 'Tech Corp',
    department: 'Development',
    jobTitle: 'Frontend Developer',
    note: 'A sample VCard entry',
    categories: ['friend', 'colleague'],
    urls: ['https://example.com'],
    photos: ['https://example.com/photo.jpg'],
    emails: ['john.doe@example.com'],
    phoneNumbers: ['+1234567890'],
    addresses: ['123 Main St, Anytown, USA'],
    impp: ['sip:john.doe@example.com'],
    geo: '37.7749,-122.4194',
    birthday: '1990-01-01',
    anniversary: '2020-01-01',
    sound: 'https://example.com/sound.mp3',
    uid: '12345',
    key: 'public-key',
  },
  {
    id: '2',
    version: '4.0',
    firstName: 'Jane',
    lastName: 'Smith',
    middleName: 'B.',
    prefix: 'Ms.',
    suffix: '',
    nickname: 'Janey',
    title: 'Project Manager',
    organization: 'Tech Corp',
    department: 'Management',
    jobTitle: 'Team Lead',
    note: 'Another sample VCard entry',
    categories: ['manager', 'colleague'],
    urls: ['https://example.org'],
    photos: ['https://example.org/photo.jpg'],
    emails: ['jane.smith@example.org'],
    phoneNumbers: ['+9876543210'],
    addresses: ['456 Elm St, Othertown, USA'],
    impp: ['sip:jane.smith@example.org'],
    geo: '40.7128,-74.0060',
    birthday: '1985-05-15',
    anniversary: '2015-06-15',
    sound: 'https://example.org/sound.mp3',
    uid: '67890',
    key: 'public-key-2',
  },
  {
    id: '3',
    version: '4.0',
    firstName: 'Brian',
    lastName: 'Topgoush',
    middleName: 'B.',
    prefix: 'Ms.',
    suffix: '',
    nickname: 'Janey',
    title: 'Project Manager',
    organization: 'Tech Corp',
    department: 'Management',
    jobTitle: 'Team Lead',
    note: 'Another sample VCard entry',
    categories: ['manager', 'colleague'],
    urls: ['https://example.org'],
    photos: ['https://example.org/photo.jpg'],
    emails: ['jane.smith@example.org'],
    phoneNumbers: ['+9876543210'],
    addresses: ['456 Elm St, Othertown, USA'],
    impp: ['sip:jane.smith@example.org'],
    geo: '40.7128,-74.0060',
    birthday: '1985-05-15',
    anniversary: '2015-06-15',
    sound: 'https://example.org/sound.mp3',
    uid: '67890',
    key: 'public-key-2',
  },
  {
    id: '4',
    version: '4.0',
    firstName: 'Jocelyne',
    lastName: 'Shroud',
    middleName: 'B.',
    prefix: 'Ms.',
    suffix: '',
    nickname: 'Janey',
    title: 'Project Manager',
    organization: 'Tech Corp',
    department: 'Management',
    jobTitle: 'Team Lead',
    note: 'Another sample VCard entry',
    categories: ['manager', 'colleague'],
    urls: ['https://example.org'],
    photos: ['https://example.org/photo.jpg'],
    emails: ['jane.smith@example.org'],
    phoneNumbers: ['+9876543210'],
    addresses: ['456 Elm St, Othertown, USA'],
    impp: ['sip:jane.smith@example.org'],
    geo: '40.7128,-74.0060',
    birthday: '1985-05-15',
    anniversary: '2015-06-15',
    sound: 'https://example.org/sound.mp3',
    uid: '67890',
    key: 'public-key-2',
  },
  {
    id: '5',
    version: '4.0',
    firstName: 'Joshua',
    lastName: 'Brinston',
    middleName: 'B.',
    prefix: 'Ms.',
    suffix: '',
    nickname: 'Janey',
    title: 'Project Manager',
    organization: 'Tech Corp',
    department: 'Management',
    jobTitle: 'Team Lead',
    note: 'Another sample VCard entry',
    categories: ['manager', 'colleague'],
    urls: ['https://example.org'],
    photos: ['https://example.org/photo.jpg'],
    emails: ['jane.smith@example.org'],
    phoneNumbers: ['+9876543210'],
    addresses: ['456 Elm St, Othertown, USA'],
    impp: ['sip:jane.smith@example.org'],
    geo: '40.7128,-74.0060',
    birthday: '1985-05-15',
    anniversary: '2015-06-15',
    sound: 'https://example.org/sound.mp3',
    uid: '67890',
    key: 'public-key-2',
  },
]

export async function GET() {
  return NextResponse.json(data)
}

export async function OPTIONS() {
  return NextResponse.json({ allow: ['GET'] }, { status: 200 })
}
